### ISSUE TITLE
Options collection empty when querying for txn using access code

### ISSUE THREAD

**Issue by justabuzz** [eWAYPayment/eway-rapid-net#1]
Hi,

I believe the issue is fairly easy to sort out, I tried to fork and build it myself, but I don't have the signing cert to complete the build.

Go to this line: https://github.com/eWAYPayment/eway-rapid-net/blob/master/eWAY.Rapid/Internals/Services/RapidService.cs#L104

Should change QUERY_TRANSACTION to ACCESS_CODE_RESULT.

Correct me if I'm wrong? :)

Thanks.

**Comment by incarnate** [comment]
Hi @justabuzz 

Thanks for the suggestion - that will indeed work to populate the `Options` collection, although at the expense of the other data that transaction query returns (which may not be an issue for you).

We're currently working on an update for Rapid API which will populate the `Options` when using transaction query, I'll update this issue once it is released. If you do need the options urgently in the meantime, you can swap in `ACCESS_CODE_RESULT` and comment out the `PublicKey`s to complete the build.

Cheers,
John

**Comment by justabuzz** [comment]
Thanks @incarnate,

After posting this issue I removed the signing of the DLLs from the project config, so I managed to build the projects. When I tried to use it I got a runtime exception coming from AutoMapper. It complained about null values when trying to map the query results.

Cheers.

**Comment by incarnate** [comment]
Ah yes, Transaction Query returns the result in an array which would break the mapping :-/

The good news is that the change to add the Options to the response from Rapid went live today, so Transaction Query will now work as you expect - no update to the SDK required!
