### ISSUE TITLE
Encryption Service 

### ISSUE THREAD

**Issue by A5hpat** [eWAYPayment/eway-rapid-net#10]
[Encryption Service](https://eway.io/api-v3/?shell#encryption-service) is not supported yet. when you guys planing to add this as i want to use it in Direct Connection to avoid PCI compliant?

**Comment by incarnate** [comment]
Hi Ashish,

The Encryption Service is for client side applications that are unable to use the [eWAY's JavaScript encryption](https://eway.io/api-v3/?shell#automatic-encryption), while this library is intended primarily for server side applications. As such, the Encryption Service won't be supported in this library.

If you are building a client side application in .NET and need some assistance with using the Encryption Service, please [contact](https://www.eway.com.au/contact-us/active-merchant) our friendly support team!
