### ISSUE TITLE
Newtonsoft.Json dependency problems since .net core 1.0

### ISSUE THREAD

**Issue by Droxx** [eWAYPayment/eway-rapid-net#13]
Since the 1.0 release of .net core. Eway.Rapid cannot be included since .net core requires Newtonsoft.Json 9.0.1. And Eway.Rapid is incompatiable with any version above 8.0.3

**Comment by incarnate** [comment]
Thanks for the opening this issue, I haven't had a chance to test this package with .NET Core yet.

I've done some quick tests and it looks like moving to Newtonsoft.Json v9.0.1 works fine. If you build this with v9.0 .1 does it work in your .NET Core project?

**Comment by incarnate** [comment]
Version 1.5.0 of the eWAY .NET SDK has just been released which uses Newtonsoft.Json 9.0.1 - I'll mark this issue closed now, but let us know if there are still any issues.
