### ISSUE TITLE
Support for latest AutoMapper and NewtonSoft packages

### ISSUE THREAD

**Issue by stevomccormack** [eWAYPayment/eway-rapid-net#14]
No support for the latest packages makes it difficult for everyone to update their entire projects. 
This has been the case for a long time.

Can you simply update the dependencies when you receive notifications?
It would make developers lives a whole lot easier.

**Comment by incarnate** [comment]
Hi Steve,

Thanks for raising the issue. 
Sorry to be a bit slow to keep up with the dependency versions. We should be able to do an update with support for the latest NewtonSoft JSON version soon, however AutoMapper has some changes that break some mappings so some reworking is needed before we can update that.

**Comment by Rajsanthosh** [comment]
@incarnate any update on the AutoMapper mapping issue, having mapping issues with my project.

All my projects in my solution uses AutoMapper 5.1.1 except for one project which uses eWay Rapid with AutoMapper version 3.3.1. However, there is an exception thrown by AutoMapper through the eWay Rapid.

Any work around to solve this issue. I can not use AutoMapper 3.3.1 for my entire solution that would require tons of changes to my solution.

**Comment by incarnate** [comment]
Hi Rajsanthosh - I've just released version 1.5.0 to move AutoMapper up to version 4.1.1 which is the last release before some incompatible changes were made. I still haven't had a chance to assess what work is needed to make the SDK compatible with AutoMapper v5+, so can't provide a timeline just yet.

**Comment by incarnate** [comment]
A beta release of eWAY .NET SDK version 1.6.0 is now available with AutoMapper 5.1.1 support.

There are some issues with mapping a customer's address in responses but otherwise everything else appears to work fine. If anything else isn't mapping properly please open an issue to let us know.

**Comment by stevomccormack** [comment]
This is a common issue incarnate! Your libraries when not updated, prevent all developers using eWay.Rapid from upgrading their projects and force them into your lowest common dependencies.

Please keep this in mind - it affects us all the time as it prevents us from upgrading.

As for AutoMapper issues - really!? It is a pretty basic library based on conventions. 
It would be worrying if you couldnt sort things out with this.

FYI - speaking with support today, I was surprised they could SYMMETRICALLY DE-CRYPT my password access to the system. Would have assumed eWay had HARDENED their security more than that and used asymmetric, one-way hashing encryption for the systems. #thumbsdown

**Comment by rollsch** [comment]
Why is this still using automapper 4.1.1 ???

Version 6.1.1 is out and I cannot use eway rapid....

**Comment by rollsch** [comment]
Pull request https://github.com/eWAYPayment/eway-rapid-net/pull/26 made for this issue with updated references and porting to the new automapper convention. All the tests pass.

I'm concerned that firstly this issues register is not monitored and secondly that no one has made any effort to keep the SDK up to date. Braintree and swype manage to keep their .NET repos up to date.

**Comment by incarnate** [comment]
Sorry again for the big delay in getting the PR released - version 1.6.0 of the eWAY .NET SDK now uses the latest versions of AutoMapper and NewtonSoft JSON.
