### ISSUE TITLE
QueryTransaction returning object will null properties

### ISSUE THREAD

**Issue by warrickw** [eWAYPayment/eway-rapid-net#15]
The following line returns a QueryTransactionResponse, but all the properties of QueryTransactionResponse are null - such as AccessCode, Transaction, and TransactionStatus. What is the scenario where this happens?

`
QueryTransactionResponse response = ewayClient.QueryTransaction(toConfirm.AccessCode)
;`

**Comment by incarnate** [comment]
Hi Warrick,

There are a couple of cases where this could happen; If an invalid AccessCode is passed then all the properties will be null (including Errors it seems). If invalid credentials are used all the properties will be blank but and there will be an Error.

If it isn't something along those lines, you can reach out to [eWAY Support](https://www.eway.com.au/contact-us/active-merchant) and they'll be able to look the issue in more depth.

**Comment by warrickw** [comment]
I'm assuming in my situation it was an invalid access code, which is weird since it originally came from eway anyway.
