### ISSUE TITLE
 Could not load file or assembly 'eWAY.Rapid, Version=1.4.0.0, Culture=neutral, PublicKeyToken=3ab6d5d95167133b' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by stevomccormack** [eWAYPayment/eway-rapid-net#16]
Due to dependency issues with library, I was forced to update to pre-release beta version that uses AutoMapper v5.*.

`Update-Package eWAY.Rapid -Pre`

Now having issues with all projects using eWay references:

`Could not load file or assembly 'eWAY.Rapid, Version=1.4.0.0, Culture=neutral, PublicKeyToken=3ab6d5d95167133b' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I've checked:

- DLL references in bin folders are all eWay.Rapid v1.6.0.0.
- package id="eWAY.Rapid" version="1.6.0-beta1" targetFramework="net451" />
- Updated all project binding redirects (which do not define any eWay bindings anyway) but just to be sure.

This exception is very common - normally associated with references not being updated or multiple versions defined (imported from projects that have not been updated). I have checked all this as above and still get exception.

Am I missing something obvious or does library have bugs?

Thanks.
Steve

**Comment by macleancherry** [comment]
Hi Steve, our Git owner is out of the office for a couple of weeks at the moment. Did you figure this out on your own or do you need further support?

Maclean
