### ISSUE TITLE
W

### ISSUE THREAD

**Issue by krishamatya** [eWAYPayment/eway-rapid-net#18]
EWAY create customer token is accepting test credit card number for live eway account and same does on update credit card.

However it doesnot allow transaction>> Really need to solve this issue as it is effecting my work

**Comment by krishamatya** [comment]
EWAY create customer token is accepting test credit card number for live eway account and same does on update credit card.

However it doesnot allow transaction>> Really need to solve this issue as it is effecting my work

**Comment by incarnate** [comment]
Hi krishamatya,

Unfortunately the only way to know if a card is valid is to process a transaction via the banking network with it. This isn't really related to the .NET SDK, if you do need further assistance with this please get in touch with our friendly customer support team: https://go.eway.io/
