### ISSUE TITLE
Sandbox no longer works after Eway changed to enforcing TLS1.2

### ISSUE THREAD

**Issue by dkiryazi** [eWAYPayment/eway-rapid-net#20]
I spoke with EWay support about a sandbox connection problem.

It appears Eway has updated the sandbox api to only accept TLS1.2 connections (a change which has not been made on production yet) and .NET does not automatically negotiate TLS1.2. I opened a PR with a code change that sets "ServicePointManager.SecurityProtocol" to TLS1.2. In hindsight, after talking to a colleague, this might of been short sighted on my part so have closed the PR.

I ran a test upgrading the project to target .NET 4.6 and .NET 4.6 seems to correctly negotiate TLS1.2.

Is anyone else experiencing this issue when connecting to sandbox and have any other suggestions to the ones I have mentioned above and in the comments in the closed PR?

Thanks,
Dave

**Comment by incarnate** [comment]
Hi @djkse 

Sorry for the slow response to your issue & PR. We made some changes and released version 1.5.2 to handle the TLS 1.2 change last week. I think our solution is similar to yours, although we're reverting the setting after each eWAY call as it is application wide and we want to avoid unintended side-effects.

Using .NET 4.6 is a neater solution as it defaults to using TLS 1.2, but sadly not always an option :-)

Cheers!

**Comment by dkiryazi** [comment]
Hi @incarnate 

Thanks for the response. Yes, I cancelled my PR once I realised the application wide effect :)

I can confirm that version 1.5.2 is working correctly with sandbox and production environments.
