### ISSUE TITLE
No support for higher version of Newtonsoft Json 10.0.2

### ISSUE THREAD

**Issue by kusumdas** [eWAYPayment/eway-rapid-net#22]
Hello Team, 

I  have used eWay-rapid-net library, but it is not working with my latest Newtonsoft Json Verson 10.0.0.

I know that it is having minimum requirement of Newtonsoft Json V9.0.1, but Is there any way through which it can work with any Newtonsoft Version which should be minimum V9.0.1 or any higher version.

Please help me , this is urgent?

regards
Kusum

**Comment by incarnate** [comment]
Hi Kasum,

Thanks for raising this issue. I've just run some tests and it looks like the move to Newtonsoft.Json v10.0.2 doesn't cause any problems.

I'll conduct some further tests and see if we can get an updated release out next week.

**Comment by incarnate** [comment]
Sorry for the delay, we've just released version 1.6.0 of the eWAY .NET SDK which supports Newtonsoft.Json v10.0.3
