### ISSUE TITLE
Method not found: AutoMapper.Mapper.CreateMap()

### ISSUE THREAD

**Issue by miki-nis** [eWAYPayment/eway-rapid-net#25]
I've tried to use this library in a .NET 4.5.2 API project but on line where I create the Rapid client:
IRapidClient ewayClient = RapidClientFactory.NewRapidClient(EwayApiKey, ApiPassword, EwayRapidEndpoint);
I get a MissingMethodException (in case it matters I use AutoMapper v5.0.2):

{  
   "Message":"An error has occurred.",
   "ExceptionMessage":"Method not found: 'AutoMapper.IMappingExpression`2<!!0,!!1> AutoMapper.Mapper.CreateMap()'.",
   "ExceptionType":"System.MissingMethodException",
   "StackTrace":"   at eWAY.Rapid.Internals.Services.MappingService.RegisterRequestMapping()\r\n   at eWAY.Rapid.Internals.Services.MappingService.RegisterMapping() in C:\\test_net\\eway-rapid-net-tls12\\eWAY.Rapid\\Internals\\Services\\MappingService.cs:line 44\r\n   at eWAY.Rapid.RapidClientFactory.NewRapidClient(String apiKey, String password, String rapidEndpoint) in C:\\test_net\\eway-rapid-net-tls12\\eWAY.Rapid\\RapidClientFactory.cs:line 23\r\n   at INBA.Api.Controllers.Members.PurchaseController.Eway(PurchaseModel model) in C:\\PROJECTS\\INBA.Api\\source\\INBA.Api\\Controllers\\Members\\PurchaseController.cs:line 61\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClassc.<GetExecutor>b__6(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by miki-nis** [comment]
When I updated the package to version 1.6.0-beta1 , I stopped getting this error

**Comment by incarnate** [comment]
Thanks for the issue @mickyinba 

The current stable version of the .NET SDK (v1.5.3) is dependent on v4.1.1 of AutoMapper still, we've had some trouble getting to the latest version due to breaks in backwards compatibility.

As you've found, we've released a beta with support for a newer version, however bear in mind it is a beta and there may be some bugs.

**Comment by incarnate** [comment]
We've just released version 1.6.0 of the eWAY .NET SDK which supports AutoMapper 6.2.0 which resolves this bug. Thanks for submitting the issue!
