### ISSUE TITLE
Automapper missing type configuration

### ISSUE THREAD

**Issue by yaozuwang** [eWAYPayment/eway-rapid-net#27]
On this line:

`            CreateTransactionResponse response = ewayClient.Create(PaymentMethod.Direct, transaction);
`

I am getting the following error:

AutoMapper.AutoMapperMappingException
Missing type map configuration or unsupported mapping. Mapping types: Object -> List`1 System.Object -> System.Collections.Generic.List`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] Destination path: CreateTransactionResponse.Errors.Errors Source value: (null)

Automapper version: 4.2.1
Eway.rapid version: 1.5.3

We don't really want to update or downgrade automapper just because of eway.rapid, which version of eway.rapid can i use with automapper 4.2.1? What is the issue, is it really because of the automapper version?

**Comment by rollsch** [comment]
The new automapper is quite different. Have a look at the pull requests and grab my fork which works with the latest automapper. EWay are not maintaining this repo. If you have a choice I would look at changing to swipe or braintree as their support is woeful.

God forbid when you want to use NETCORE, probably be years before they support that!

**Comment by incarnate** [comment]
Hi @yaozuwang - sorry for the delay, we've just released version 1.6.0 of the eWAY .NET SDK which supports AutoMapper 6.2.0. Can you see if this resolves your issue?
