### ISSUE TITLE
eWAY.Rapid client Query Customer not returning any card details .

### ISSUE THREAD

**Issue by praveenbarawal** [eWAYPayment/eway-rapid-net#29]
Hi,

eWAY.Rapid client Query Customer not returning any card details . 
I m using mvc and eway 1.6.0.0 dll and auto mapper dll 6.2.1.0.

Please suggest
Thanks & Regards
Praveen Barawal

**Comment by incarnate** [comment]
Hi Praveen,

Thanks for raising this issue! We've just released version 1.6.1 of the eWAY .NET SDK with a fix for the missing card data when creating or querying token customers.

**Comment by praveenbarawal** [comment]
Thank you very much for your support.

**Comment by praveenbarawal** [comment]
Hi,

Thanks for your kindly support, but it's really too late to fix the issue.
Please try to resolve the issue quickly in future because we have limited
period of time to deliver the product to the client.

*Thanks & Regards*

*Praveen Barawal*

*Software Engineer*

*Mobile:- +91 9034347263*

*Phone: +91-124-4921831 <+91%20124%20492%201831> |
E-mail: praveen.barawal@sonartechnologies.com
<praveen.barawal@sonartechnologies.com>| Web: **www.sonartechnologies.com
<http://www.sonartechnologies.com/>*

1130,  JMD Megapolis, Sohna Road, Sector-48, Gurgaon, Haryana-122018
