### ISSUE TITLE
RequestMethod missing from Transaction?

### ISSUE THREAD

**Issue by ianleeder** [eWAYPayment/eway-rapid-net#3]
I see there is an enum for RequestMethod, but I can't find a way to use it in a Transaction.  In fact, searching the entire repo I don't see it used anywhere.

There is a duplicate enum under eWAY.Rapid.Internals.Enums.Method, and that gets used (such as eWAY.Rapid.Internals.Request.CreateAccessCodeRequest), but these are obviously unavailable.  What is the correct method for setting the RequestMethod in a Transaction?  The API doesn't show an example of actually doing this.

**Comment by incarnate** [comment]
Hi Ian,

The RequestMethod is set implicitly in the eWAY SDKs; so rather than specifying it in a request, it is set based on the call being made.

For example, calling `create` with a customer object will automatically use `CreateTokenCustomer`. Creating a transaction with the `capture` parameter set to `false` will result in `Authorise` being used.

Please let us know if you need any further details!

**Comment by ianleeder** [comment]
Thanks Incarnate, I really appreciate the help.  ~~I'm not exactly sure what you mean by `create` with the customer object?~~
I see, you mean on the IRapidClient instance.  I hadn't realised there were various options there, however I am using create (as I'm following the API examples still).

(This is all Sandbox btw) In my case we charge a regular subscription fee.  In order to get users into the system we charge $1 (so a valid transaction has been approved with CVN) before using the recurring payments.  So I am trying to do a TokenPayment type purchase for $1, however I'm not getting a CustomerTokenID back, only null.

As above I'm using Create, and TransparentRedirect.  My TransactionType is Purchase with all necessary fields filled in.  I'm not getting any errors, I get back a valid response, just no customer token ID.  What am I missing?

Is it because I'm passing a transaction and not just a customer?  The API indicates it's possible to do both at once:

> TokenPayment: This method allows merchants to process payments using Token customers they have stored with eWAY. Merchants can either load an existing token customer by passing in their TokenCustomerID in the initial request, **or create a new Token customer by leaving the TokenCustomerID field blank (Transparent Redirect and Responsive Shared Page only).**

**Comment by incarnate** [comment]
Thanks for the additional detail Ian, it does look like being able to create & charge using `TokenPayment` is missing from the .NET SDK at the moment.

We're looking at the best way to deal with that scenario. I'm thinking maybe of adding a `CreateToken` flag to the Transaction object similar to the way `Capture` can be used to flag if the transaction should be a pre-auth. If you've thoughts they are welcome!

**Comment by ianleeder** [comment]
I don't have the experience as a developer nor the familiarity with this package to provide a useful suggestion.  With that said, my 1 cent (not worth 2) would be to consider implementing it as per the API, save a lot of documentation updates.  Not sure why this Method/RequestMethod is now hidden and implicit.

Additionally, calling `ewayClient.Create(PaymentMethod.TransparentRedirect, customer);` doesn't return a token ID either.

**Comment by ianleeder** [comment]
Do you have an estimate for when these issues might be rectified?  I don't know whether I should continue trying to use the SDK, or revert to making all the web calls directly (as per the downloadable samples).

Also, the label should be updated from Question to Bug.

**Comment by incarnate** [comment]
Hi Ian,
We're working on this change alongside a couple of others for the .NET SDK - at the moment I'd say we should have a release ready at the end of next week.

To answer your earlier question, token IDs are only created after the card details have been passed to eWAY. So `Create(PaymentMethod.TransparentRedirect, customer)` won't return a token ID as no card details are collected at that point.

**Comment by ianleeder** [comment]
Thanks for the update.  I think you may have answered my question!
This is the key _"token IDs are only created after the card details have been passed"_.

I hadn't realised the tokenID was only returned after payment had been sent, I misread that section of the API.  I was so caught up in the various descriptions telling me how to create one:

> Any values passed in the Customer part of the **initial** request will be used to either create or update the Token customer, depending on the TokenCustomerID value.

that I misread the response.  

> The token customer’s unique Token Customer ID. **Only returned if included in the request** with TokenPayment and UpdateTokenCustomer methods

I hadn't actually processed the payment yet, just submitted the transaction (designated Step 1 in the API).  It appears I need to complete payment (Step 2), then fetch a response (Step 3) in order to get the customer Token ID.

Plus it was telling me that the Transaction Method (e.g. TokenPayment to generate a token) is a required field, so I kind of focused on that too.

~~Although knowing that's the case, I am unclear what the purpose of `Create(PaymentMethod.TransparentRedirect, customer)` is if not to generate a token.~~
Duh.  You _do_ generate a token, by submitting card details with a $0 transaction <facepalm>

**Comment by ianleeder** [comment]
So my current understanding is that:
- I was misunderstanding how tokens were generated, and expecting one before payment details were submitted, BUT
- Even after submitting payment details you still don't receive a token.

Am I missing anything?

I've knocked up some code to test it full from go to whoa, see [linked Gist](https://gist.github.com/ianleeder/e09c440998c0019c6ef3#file-ewaytest-cs).  Whether sending a transaction or a customer, even after card details are sent, CustomerTokenID is null.

Am I (still) missing anything?

**Comment by ianleeder** [comment]
Right, I figured out how to purge my test data in the Sandbox.  For the linked Gist, TestCustomer does indeed generate a CustomerTokenId in the Sandbox, but it does not return it.  TestTransaction does neither.

**Comment by incarnate** [comment]
Sorry to be slow to reply, I've been out of the office for the last few days.

It looks like you've identified the issue - the mapping from the API response to the response objects are dropping the TokenCustomerID along the way. We're working on a fix for that which we should be able to roll out soon. Thanks for all your efforts on this!

**Comment by ianleeder** [comment]
FYI AccessCode gets dropped as well.  I obviously don't need it by that point (required it to make the QueryTransaction in the first place) but the API says it will be returned.

**Comment by incarnate** [comment]
Hi Ian,

I've just pushed version 1.2.0 of the eWAY .NET SDK to NuGet - this should contain all the updates needed for your application:
- A new field has been added to the `Transaction` object: `SaveCustomer`. When set to true, a token customer will be created when a Responsive Shared or Transparent Redirect transaction is completed.
- The token ID is now available in the transaction response when one is created, this can be found in `response.Transaction.Customer.TokenCustomerID`

The SDK actually uses the [Transaction Query](http://eway.io/api-v3/?csharp#transaction-query) API to fetch the result, so no AccessCode is returned with that response.

I'm finishing up the documentation updates to go along with this now and they should be live soon. If you've any questions please let us know!

**Comment by ianleeder** [comment]
Great, thanks a lot for that.  I'll try it out tomorrow.

**Comment by ianleeder** [comment]
Great, that did the job, I'm now able to generate and read back customer tokens.  Thanks for your help with this.

**Comment by incarnate** [comment]
Happy to hear that it is all working for you now Ian, thanks for your patience while we worked it all out!

**Comment by ianleeder** [comment]
One more question, where do I go for help/to report errors with the server-side responses?  I'm running into grief with a response message which is clearly wrong (V6014 - Invalid Payment InvoiceReference.  I'm playing with Paypal, I think maybe it's a typo and should be V6141).

**Comment by lexjwa** [comment]
Hi Incarnate
I am new to eWay. I have a question. 
What should I do to remove pre-auth layer? We are using token payments, and want to remove pre-auth layer so we do not get charge for this layer.

Does creating a transaction with the capture parameter set to true will result in stop Authorise being used

**Comment by incarnate** [comment]
Hi @Sakandar 
If you set `Capture` to true then the SDK will perform a purchase rather than a pre-authorisation, yes.

Feel free to open a new issue if you've questions rather then adding to a closed one - or you can [chat to our friendly support team](https://www.eway.com.au/contact-us/active-merchant) directly.
