### ISSUE TITLE
Fields not returned on Purchase

### ISSUE THREAD

**Issue by ianleeder** [eWAYPayment/eway-rapid-net#4]
Back again with another one for you incarnate.

When you create a transaction of the type Purchase, the InvoiceDescription and CurrencyCode aren't returned (as per [the API](https://eway.io/api-v3/?csharp#transparent-redirect)).  However when you perform a transaction of the type Recurring, it works fine.  See [this linked GIST](https://gist.github.com/ianleeder/a977ad896a858c3a9d3b).

The irony is that Purchase is a manual transaction where the end user is involved and would actually like to see the Description in the results page.  A recurring transaction typically happens behind the scenes and doesn't involve user interaction.

Edit: I've also logged another defect about paying via Paypal.  This one is the lower priority (and probably easier fix for you).  This is a nice to have, but #5 is important.

**Comment by incarnate** [comment]
Hi Ian,

It looks like this is more a difference between the Direct and Transparent Redirect payment methods. 

We have introduced [versioning](https://eway.io/api-v3/?shell#versions) for Rapid API so we can add/change fields safely, and CurrencyCode is one of the fields that is available already. I've just made a request for InvoiceDescription to be added. 

I've been working on adding versioning to the eWAY SDKs, however we've got some field conflicts to work out before they can be released. There isn't a timeframe for this yet I'm afraid. I'll update this issue as more details are available.

**Comment by ianleeder** [comment]
Sounds like a step in the right direction.  Not in any hurry for this one, it just adds a nice touch to the results page for the customer.

**Comment by ianleeder** [comment]
Any update on when versioning will be available in the .NET SDK?

**Comment by incarnate** [comment]
Nothing firm as yet, I was hoping there'd be some changes to the new response fields so they don't conflict with request fields, but maybe it'll just be easier to work around them. i should have some time next week to look closer, thanks for following up Ian.

**Comment by incarnate** [comment]
Hi Ian,
Sorry this took a lot longer than I originally thought to get out. Version 1.4.0 has just been released which supports using Rapid versioning and the new [Transaction Query fields](https://eway.io/api-v3/#versions).

```
IRapidClient ewayClient = RapidClientFactory.NewRapidClient(apiKey, password, rapidEndpoint);
ewayClient.SetVersion(40);
```

I'll mark this issue closed now since any further changes to fields will need to happen in the API.

**Comment by ianleeder** [comment]
Not too sure about this.  I just tested it, and when I submit currency code "EUR", I get returned currency code "978".  "USD" returns "840".  Any hints what's going on?  I expected the same currency code back, is it the API or the SDK returning numeric codes?  Where can I find the lookup table for these?

**Comment by incarnate** [comment]
Hi Ian,

Sorry, yes the currency is currently returned as the [ISO 4217 numeric code](https://en.wikipedia.org/wiki/ISO_4217#Active_codes) as described in the [API Reference](https://eway.io/api-v3/#transaction-query). I'd prefer that the code were the same as the alpha value used in other fields, however now the field is live and in use as is it will be hard to change.

I'll follow up if we're thinking of changing, and if not will look at adding a translation to the SDK. In the meantime this [SO question](http://stackoverflow.com/q/1156159/628267) or [NodaMoney](https://github.com/remyvd/NodaMoney) contain translations.

**Comment by ianleeder** [comment]
Ok, thanks for the explanation.  I'll perform a lookup.
