### ISSUE TITLE
Errors with paying via Paypal

### ISSUE THREAD

**Issue by ianleeder** [eWAYPayment/eway-rapid-net#5]
Paying with Paypal was the easiest thing in the world to set up.  And yet sometime in the last few weeks it has stopped working.  I suspect something in their API (or yours) has changed, because I don't believe I have changed anything.  [This gist](https://gist.github.com/ianleeder/21f0afda2b1dde48d6f4) is a very quick and easy test case to show what happens.  It doesn't even worry about a results page, as we don't get that far.  The redirect to Paypal fails and Paypal shows an error page:
![Paypal error screen](https://cloud.githubusercontent.com/assets/8241300/12903916/abaf99da-cf1f-11e5-9574-33634e34c80f.png)

Can you shed any light on the issue?

**Comment by incarnate** [comment]
Hi Ian - is this in Sandbox? There is an issue with PayPal in Sandbox at the moment due to some changes in SSL certificates that should be resolved later this week.

**Comment by ianleeder** [comment]
Yes, this is the sandbox.  That's great news, thanks for the update.  I'll leave this open until the issue is resolved.

**Comment by ianleeder** [comment]
Any updated (reliable) timeframe on this?

**Comment by incarnate** [comment]
Hi Ian - sorry for the delay, I've followed up with the team on this issue. 
The fix is part of a larger change-set which is still in testing, so while the aim is to have it out this week, I wouldn't say the timeframe is reliable since it depends how the testing pans out. I'll update this issue when we have something more concrete.

**Comment by ianleeder** [comment]
Thanks, appreciate the honesty.

**Comment by ianleeder** [comment]
This is now working again.
