### ISSUE TITLE
Improvement suggestion re Customer.getTokenCustomerID()

### ISSUE THREAD

**Issue by ianleeder** [eWAYPayment/eway-rapid-net#8]
Was just looking through the recent commit: I like the `hasFraudCode` and `getResponseMessages`.  But the `Customer.getTokenCustomerID()` seems flawed.  `public long? TokenCustomerID` is a `nullable long`, so calling `TokenCustomerID.ToString()` without a null check is just asking for trouble.  Suggest you change it to `return (TokenCustomerID == null) ? null : TokenCustomerID.ToString();`.  Or return `""`, either is better than a `NullReferenceException`.

Of course, the method itself seems redundant to me, but perhaps you have longer-term plans for it.

**Comment by incarnate** [comment]
Good pickup thanks Ian, I've added that improvement for the next release. This method may be redundant, I was thinking of the Java SDK where the types aren't as consistent as they could be.
