### ISSUE TITLE
Updating stored payment details when processing a payment

### ISSUE THREAD

**Issue by ianleeder** [eWAYPayment/eway-rapid-net#9]
(Still the sandbox)
We provide a subscription based service.  Whenever I create a customer or change payment details we like to do so with a $1 purchase transaction to try and minimise any chances of future recurring payments being denied.

I can create a new customer and save their details using a (transparent redirect) purchase transaction.
I can also update their credit card details using a purchase transaction.
However I can't update Paypal details using a purchase transaction.
(I haven't tested other payment methods yet, Visa Checkout or MasterPass)

I'm not sure what the intended behaviour is here.  If you are **not** meant to be able to update details via a purchase, then the credit card behaviour is wrong.  If you **are** meant to be able to update stored details via a purchase, the Paypal behaviour is wrong.

It took me a little while to work out exactly what was going on, so the [linked Gist](https://gist.github.com/ianleeder/2bf770ff70a5a9288f13) might be a little bit of overkill.  However it has proven handy for testing.  On each run it will register a new customer, then continue to update/charge that customer token until you click "Start over".

If you already have Paypal details on record, attempting to process a Payment (Transparent Redirect) with Paypal simply processes it using the stored credentials, it doesn't ask for new ones.  Process to duplicate:
- Register with Paypal ($1)
- Submit recurring payment ($5)
- Verify in MYeWAY that transaction was charged to Paypal account
- Update details without payment, select Paypal
- eWAY correctly redirects to Paypal login page to provide new credentials.
- MYeWAY shows authorisation transaction for $0
- Update details with payment ($6), select Paypal
- No Paypal login screen presented, simply charged to most recent account

Similarly, if you try to process a Paypal payment on an account with no stored Paypal information, you get D4406 - "Error" (I searched Github for D4406 and found no places it gets raised, only the definition).  Process to duplicate:
- Register with credit card ($1)
- Update details via payment ($6), select Paypal
- Receive error D4406 - Error

Lengthy yes, but I like to think of it as _thorough_.

**Comment by incarnate** [comment]
Hi Ian,

Thanks for the thorough report! I've been able to replicate the behaviour you've seen with updating customers with PayPal.

When updating a PayPal token, it might be better to do an just an update rather than update+purchase. The alternative would be to make a significant change to eWAY's payment flow for PayPal and redirect all token payments to PayPal in case the customer wants to update their details. If you want to verify the account you could immediately do the payment against the token.

I'll raise with our dev team the issue of updating a credit card to a PayPal token. I can't say how long a fix like that may take, you might want to treat credit card and PayPal as separate tokens for now. It may not work for your setup, but in our plugins we'll usually allow a customer to store multiple tokens so they can choose one as needed.

And D4406 is a generic error code for cases where there isn't a specific error code to use - this most often comes up with PayPal as we can't always have something mapped for their many error codes.

**Comment by ianleeder** [comment]
Funnily enough when updating Paypal with no payment, Paypal make it very clear that you are authorising for future payments.  So I don't expect any issue when doing update only for Paypal.  The concern is that if we do update only for credit card, the first time it is used for a purchase it may be declined by the bank (especially since we deal with international customers).

However the way we've structured the site (and indeed it seems the correct way to use eWAY) is to set up the transaction type first, then let the customer choose the payment method.  By that stage the transaction is transparent to me (details sent directly to eWAY), so not only do I now know how they pay (this is very annoying btw, but I'll send that rant elsewhere), it's too late to change the request to eWAY.

I like your idea of doing an update only, then immediately running a $1 transaction.  It will be easier to implement than having them select the payment method up-front, and generating different transactions with eWAY depending on selection.

How would you like me to deal with this issue?  You've indicated that you _should_ be able to update details with a payment, but also that it's largely a back-end fix rather than a .NET SDK issue.  Shall I close this and assume you have another defect open elsewhere?

**Comment by incarnate** [comment]
It sounds like performing the test transaction after the creation/update of the token will be the best way for your situation. This also means if you aren't as concerned about testing PayPal accounts, you can skip doing the $1 transaction at that point. It also works around the issue of updating credit card tokens to PayPal, plus allows changing between PayPal accounts.

I have opened a task to fix the card to PayPal issue. I'm not sure there is much we can do about performing an update to an alternate PayPal account & charge without some significant changes to the payment process however.

**Comment by ianleeder** [comment]
> This also means if you aren't as concerned about testing PayPal accounts, you can skip doing the $1 transaction at that point

Not true.  I don't know what payment method was submitted since it was transparent, and eWAY doesn't return it.  I can't even infer the payment details stored since a payment wasn't submitted (normally I check for an authorisation number which is only present on credit card transactions).

That aside, I'm happy to do it this way except for the issues hit in #11 :pensive:

**Comment by incarnate** [comment]
Fair point!
One work around for now is to do a token customer query of the new token, I believe PayPal tokens will have blank card details and card tokens will have a masked card number. But this would also mean an extra API call.

**Comment by ianleeder** [comment]
Nice try, but wrong again.  If the customer has ever had a card stored those details will be returned, even if the current stored payment method is Paypal.

It really appears Paypal was an afterthought, from the MYeWAY customer pages to the API calls, none of it caters for payment methods other than credit card.
